TOOLS-146 TOOLS-197 TOOLS-196 tunnel logging improved
hazelops/ize pull request #105
Opened 2022-01-27 09:56 UTC by psihachina

## Changelog:
- tunnel logging improved

## Test:
[![asciicast](https://asciinema.org/a/9ItMfvWUCeT7fBnD0Vl21MHVJ.svg)](https://asciinema.org/a/9ItMfvWUCeT7fBnD0Vl21MHVJ)

2022-01-28 20:35 UTC, AutomationD requested changes
Thanks, looks good, but some typos. 

Also, I'm not sure what it means when I see "can't get options". Maybe there is a way to rephrase it so it's more obvious for the user?

2022-01-28 20:35 UTC, AutomationD commented on internal/commands/tunnel/tunnel.go
> +		return fmt.Errorf("can`t complete options: %w", err)
backtick (`) shouldn't not be used instead of apostrophe (`'`), let's update please

2022-01-28 20:35 UTC, AutomationD commented on internal/commands/tunnel/tunnel.go
> +		logrus.Fatalf("%s is directory", path)
```suggestion
		logrus.Fatalf("%s is a directory", path)
```

2022-01-28 20:35 UTC, AutomationD commented on internal/commands/tunnel/tunnel_sshkey.go
> +		return fmt.Errorf("can`t complete options: %w", err)
```suggestion
		return fmt.Errorf("can't complete options: %w", err)
```

2022-01-28 20:35 UTC, AutomationD commented on internal/commands/tunnel/tunnel_sshkey.go
> +		return fmt.Errorf("can`t complete options: %w", err)
But honestly from the user standpoint I'm not sure what this error means.

2022-01-28 20:35 UTC, AutomationD commented on internal/commands/tunnel/tunnel_status.go
> +		return fmt.Errorf("can`t complete options: %w", err)
```suggestion
		return fmt.Errorf("can't complete options: %w", err)
```

2022-01-28 20:35 UTC, AutomationD commented on internal/commands/tunnel/tunnel_up.go
> +		return fmt.Errorf("can`t complete options: %w", err)
```suggestion
		return fmt.Errorf("can't complete options: %w", err)
```

2022-01-29 06:51 UTC, psihachina commented
@AutomationD where do you see "can't complete"?

2022-01-29 06:52 UTC, psihachina commented
@AutomationD

Where do you see "cant get options"?

2022-01-31 08:03 UTC, merged