TOOLS-136 add forward-host and bastion id flags
hazelops/ize pull request #117
Opened 2022-02-02 15:49 UTC by psihachina

## Changelog:
- add forward-host and bastion id flags

## Test:
[![asciicast](https://asciinema.org/a/BvDF09waFKo3HuTPuiG1XfLdX.svg)](https://asciinema.org/a/BvDF09waFKo3HuTPuiG1XfLdX)

2022-02-03 11:02 UTC, AutomationD requested changes
Looks good, I've suggested minor changes in names and messages.

2022-02-03 11:02 UTC, AutomationD commented on internal/commands/tunnel/tunnel.go
> +		return fmt.Errorf("cat't complete options: for forward-host should be specified bastion host id")
Let's make it more user-oriented:
```suggestion
		return fmt.Errorf("cat't establish tunnel: --forward-host parameter requires --bastion-instance-id")
```

2022-02-03 11:02 UTC, AutomationD commented on internal/commands/tunnel/tunnel.go
> +		return fmt.Errorf("cat't complete options: for bastion host id should be specified forward-host")
```suggestion
		return fmt.Errorf("cat't establish tunnel: --bastion-instance-id requires --forward-host parameter ")
```

2022-02-06 06:45 UTC, psihachina commented on internal/commands/tunnel/tunnel.go
> +		return fmt.Errorf("can't complete options: %w", err)
@AutomationD  This prefix is ​​necessary for bug locating and ease of testing.

2022-02-07 08:04 UTC, AutomationD approved these changes
Looks good, thank you

2022-02-07 08:06 UTC, merged