TOOLS-72 TOOLS-75 external tools validation
hazelops/ize pull request #15
Opened 2021-10-27 08:59 UTC by psihachina

This commits adds:
- external tools validation 
- installing SSM Agent automatically 

Example: 

Windows 11 SSM Agent
![image](https://user-images.githubusercontent.com/47272597/139033249-5b3de728-d2de-4d1d-a4f3-7deecf643f8e.png)

Ubuntu (wsl2) SSM Agent
[![asciicast](https://asciinema.org/a/6LgGPojgEgBlNsAykFwnoUvBt.svg)](https://asciinema.org/a/6LgGPojgEgBlNsAykFwnoUvBt)

Ubuntu (wsl2) Docker
[![asciicast](https://asciinema.org/a/8IozlqwC52HZ3Nt8qWBhlwrFO.svg)](https://asciinema.org/a/8IozlqwC52HZ3Nt8qWBhlwrFO)

Windows 11 Docker
![image](https://user-images.githubusercontent.com/47272597/139034023-ba8e5ee1-f1ed-4920-bf7c-1a113a55f073.png)

### Not tested on MasOS

2021-10-30 14:03 UTC, AutomationD requested changes
Looks good, minor changes requested.

2021-10-30 14:03 UTC, AutomationD commented on internal/commands/base.go
> +		return errors.New("docker is not running or is not installed")
Also let's provide to ssm plug-in installation a link in the place where we notify user to install the plugin manually.

2021-10-30 14:13 UTC, psihachina commented on internal/commands/base.go
> +			return fmt.Errorf("cleanup SSM Agent error: %v", err)
@AutomationD https://staticcheck.io/docs/checks#ST1005

2021-10-30 14:43 UTC, psihachina commented on internal/commands/base_init.go
> +		return "", fmt.Errorf("error looking for a Ize configuration: %s", err)
@AutomationD https://staticcheck.io/docs/checks#ST1005

2021-11-01 07:24 UTC, AutomationD approved these changes
LGTM

2021-11-01 07:26 UTC, merged