IZE-105 ize help is reviewed updated extended (env, deploy, init)
hazelops/ize pull request #162
Opened 2022-02-28 12:43 UTC by psihachina

## Changelog:
- expand descriptions of global flags
- add long descriptions and examples to env command
- add descriptions and examples to deploy commands

## Test:
### Not required

2022-02-28 13:38 UTC, kobrikx requested changes
Look good, but need to change some typos.

2022-02-28 13:38 UTC, kobrikx commented on internal/commands/deploy/deploy.go
> +	For deploy service the service name must be specified.
Service name must be specified for a service deploy.

2022-02-28 13:38 UTC, kobrikx commented on internal/commands/deploy/deploy_infra.go
> +	Deploy only infraftructure.
Only deploy infrastructure

2022-02-28 13:38 UTC, kobrikx commented on internal/commands/ize.go
> +	rootCmd.PersistentFlags().StringP("env", "e", "", "(required) set enviroment name (overrides value set in ENV / IZE_ENV if any of them are set)")
environment

2022-02-28 15:28 UTC, igorkotof approved these changes

2022-03-04 08:20 UTC, AutomationD approved these changes
LGTM

2022-03-04 08:27 UTC, merged