IZE-303-run-end-to-end-integration-tests-during-pr-via-ci-cd
hazelops/ize pull request #302
Opened 2022-05-26 16:27 UTC by kobrikx

#### What's new:

 -  Added smoke-tests initial

2022-05-26 16:29 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +name: "Smoke tests"
I'd make it simple:
```suggestion
name: "Tests"
```

2022-05-26 16:30 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +  Bastion:
```suggestion
  Tunnel:
```

2022-05-26 16:37 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
>        - name: Ize build
It's all about ize, so let's not abuse the name.
```suggestion
      - name: Build
```

2022-05-26 19:31 UTC, kobrikx commented on .github/workflows/smoke_tests.yml
> +  Ecs_Apps:
changed to ecs_apps

2022-05-26 19:43 UTC, kobrikx commented on .github/workflows/smoke_tests.yml
>          run: go build -o ./ize ./cmd
We have matrix (ubuntu & macos)  - how do you intend to use artifact with matrix ?

2022-05-30 07:44 UTC, AutomationD requested changes

2022-05-30 07:44 UTC, AutomationD commented on examples/ecs-apps-monorepo/.ize/env/testnut/ize.toml
> +aws_profile = "default"
Let's not use profile in ize.toml in the examples please

2022-05-30 07:44 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +# mv testnut $env
Let's remove this

2022-05-30 07:44 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +          AWS_PROFILE: test-terraform
Any reason not to used default here?

2022-05-30 07:44 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +          AWS_PROFILE: ecs-apps-monorepo
Any reason not to use `default` here?

2022-05-30 07:44 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +          AWS_PROFILE: test-ecs-apps
any reason not to use `default` here?

2022-05-30 07:44 UTC, AutomationD commented on .github/workflows/smoke_tests.yml
> +      AWS_PROFILE: test-ecs-apps
`default`?

2022-05-31 07:56 UTC, psihachina approved these changes

2022-05-31 07:57 UTC, AutomationD approved these changes
Looks good

2022-05-31 08:30 UTC, merged