IZE-391 IZE-392 describe new structures for new file configuration design
hazelops/ize pull request #374
Opened 2022-06-30 07:31 UTC by psihachina

## Changelog:
- rename projects folder to apps folder in example ecs-apps-monorepo
- describe new structures for new file configuration design
- rename `projects_path` parameter to `apps_path`

## Test:
#### apps_path
[![asciicast](https://asciinema.org/a/SclUsh3KbqoIlWSAGbWx4Z5L3.svg)](https://asciinema.org/a/SclUsh3KbqoIlWSAGbWx4Z5L3)

#### new structures
[![asciicast](https://asciinema.org/a/IXWMcvG8Y6a1Uf54WrwVRtPb4.svg)](https://asciinema.org/a/IXWMcvG8Y6a1Uf54WrwVRtPb4)

2022-06-30 09:34 UTC, AutomationD requested changes
Looks good, I had a quick note about default path and questions about schema fallback

2022-06-30 12:00 UTC, psihachina commented on internal/schema/ize-spec.json
>              "type": "string"
must work, i used only viper and it must supported any file format

2022-06-30 12:05 UTC, psihachina commented on internal/schema/ize-spec.json
> +            "patternProperties": {
I tried to describe the old structure in a schema, but we wanted to convert it into new structures after reading the old structure. The next step is to write a "converter"

2022-06-30 12:27 UTC, psihachina commented on internal/config/config.go
> +	viper.SetDefault("APPS_PATH", filepath.Join(cwd, "apps"))
@AutomationD 
[![asciicast](https://asciinema.org/a/2lj1J0DpeOOtJR42lZQw6DrBK.svg)](https://asciinema.org/a/2lj1J0DpeOOtJR42lZQw6DrBK)

Is that okay?

2022-07-01 08:37 UTC, AutomationD approved these changes

2022-07-01 08:38 UTC, merged