new default state bucket name
hazelops/ize pull request #430
Opened 2022-08-23 10:57 UTC by psihachina

## Changelog:
- new default state bucket name

## Test:
[![asciicast](https://asciinema.org/a/Z3oFDHvyYFrbAp3nC9U1vp3SZ.svg)](https://asciinema.org/a/Z3oFDHvyYFrbAp3nC9U1vp3SZ)

2022-08-25 15:55 UTC, AutomationD requested changes

2022-08-25 15:55 UTC, AutomationD commented on internal/commands/gen/tfenv.go
> +func checkTFState(sess *session.Session, name string) bool {
This function seems to be checking the existence of a lock but not S3 bucket.

The goal is to check if bucket exists (old code) and use that. If the bucket doesn't exist - use new defaults.
If it is set via parameters then use that value.

Does it make sense?

2022-08-26 06:37 UTC, psihachina commented
@AutomationD 
[![asciicast](https://asciinema.org/a/eIi3QLvnawvZbiLuqirE69GOC.svg)](https://asciinema.org/a/eIi3QLvnawvZbiLuqirE69GOC)

2022-08-26 07:48 UTC, AutomationD requested changes

2022-08-26 07:48 UTC, AutomationD commented on internal/commands/gen/tfenv.go
> +		exist := checkTFState(project.Session, fmt.Sprintf("%s-tf-state", project.Namespace))
```suggestion
		legacyBucketExists := checkTFStateBucket(project.Session, fmt.Sprintf("%s-tf-state", project.Namespace))
```

2022-08-26 07:48 UTC, AutomationD commented on internal/commands/gen/tfenv.go
> +		if exist {
```suggestion
		if legacyBucketExists {
```

2022-08-26 07:48 UTC, AutomationD commented on internal/commands/gen/tfenv.go
> +func checkTFState(sess *session.Session, name string) bool {
```suggestion
func checkTFStateBucket(sess *session.Session, name string) bool {
```

2022-08-26 07:48 UTC, AutomationD commented on internal/commands/gen/tfenv.go
> +			tf.StateBucketName = fmt.Sprintf("%s-tf-state", project.Namespace)
```suggestion
			// If we found an existing bucket that conforms with the legacy format use it.
			tf.StateBucketName = fmt.Sprintf("%s-tf-state", project.Namespace)
```

2022-08-26 07:48 UTC, AutomationD commented on internal/commands/gen/tfenv.go
> +			tf.StateBucketName = fmt.Sprintf("%s-%s-tf-state", project.Namespace, *resp.Account)
```suggestion
			// If we haven't found an existing legacy format state bucket use a <NAMESPACE>-<AWS_ACCOUNT>-tf-state bucket as default (unless overriden with other parameters.
			tf.StateBucketName = fmt.Sprintf("%s-%s-tf-state", project.Namespace, *resp.Account)
```

2022-08-29 06:34 UTC, AutomationD approved these changes
Looks good, thank you!

2022-08-29 07:03 UTC, merged