refactor term and ssmsession modules
hazelops/ize pull request #435
Opened 2022-08-24 16:00 UTC by psihachina

## Changelog:
- refactor term and ssmsession modules
- fix `ize console` and `ize exec`

## Test:
[![asciicast](https://asciinema.org/a/yNXQLru8MV7pU7maxEQWgIAuJ.svg)](https://asciinema.org/a/yNXQLru8MV7pU7maxEQWgIAuJ)

2022-08-24 18:18 UTC, kobrikx approved these changes
Test looks good for me!

2022-08-24 18:31 UTC, AutomationD requested changes
Looks good. 
Let's run new E2E tests on this, please merge from main to get new changes for them.

2022-08-29 06:43 UTC, AutomationD requested changes
Build is failing, please  make sure it succeeds and re-submit.

2022-08-29 06:43 UTC, AutomationD commented on pkg/term/interactive.go
> +	// Ignore interrupt signal otherwise the program exits.
```suggestion
	// Ignore interrupt signal (otherwise the program exits).
```

2022-08-29 06:43 UTC, AutomationD commented on internal/commands/tunnel/tunnel_up.go
> +	_, err := ec2instanceconnect.New(sess).SendSSHPublicKey(&ec2instanceconnect.SendSSHPublicKeyInput{
👍🏻 Thanks for this.
Please confirm this is an idempotent function and every time we execute it it writes the key only once.

2022-08-29 07:48 UTC, psihachina commented on pkg/term/interactive.go
> +	// Ignore interrupt signal otherwise the program exits.
fix typo

2022-08-29 18:18 UTC, psihachina commented
[![asciicast](https://asciinema.org/a/m2U4tzgKAxc82mhp89D1xMzZj.svg)](https://asciinema.org/a/m2U4tzgKAxc82mhp89D1xMzZj)

2022-08-30 08:08 UTC, AutomationD approved these changes

2022-08-30 08:08 UTC, AutomationD commented
Looks good, thank you!

2022-08-30 08:13 UTC, merged