IZE-667 added another ssh key for tunnel test
hazelops/ize pull request #506
Opened 2022-10-19 07:17 UTC by psihachina

## Change:
added another ssh key for tunnel test

2022-10-19 07:47 UTC, igorkotof approved these changes

2022-10-19 08:28 UTC, AutomationD approved these changes

2022-10-19 08:29 UTC, AutomationD requested changes

2022-10-19 08:29 UTC, AutomationD commented on test-e2e/bastion_tunnel_test.go
> +	stdout, stderr, err := ize.RunRaw("tunnel", "up", "--ssh-public-key", "~/.ssh/id_rsa_tunnel_test.pub")
Doesn't seem right. It should contain both private and public key in order for the test to be correct

2022-10-26 06:17 UTC, igorkotof approved these changes

2022-10-27 10:09 UTC, merged