[WIP] IZE-673 allow empty maps in viper
hazelops/ize pull request #507
Opened 2022-10-19 08:17 UTC by psihachina

## Change:
allow empty maps in viper

## Test:
[![asciicast](https://asciinema.org/a/PCCGs5YIYNmYzdFkpCLoCqzrc.svg)](https://asciinema.org/a/PCCGs5YIYNmYzdFkpCLoCqzrc)

2022-10-19 08:19 UTC, igorkotof approved these changes
LGMT

2022-10-19 08:21 UTC, AutomationD requested changes

2022-10-19 08:37 UTC, AutomationD commented
> LGMT

TMLG

2022-10-19 16:28 UTC, AutomationD commented on go.mod
> +// spf13/viper ignore empty map
Pls fix grammar

2022-10-31 22:42 UTC, AutomationD reviewed
Are there any risks with this PR and our fork?

2023-04-20 11:37 UTC, closed without merging