Refactor Secrets & update pterm style
hazelops/ize pull request #82
Opened 2022-01-15 20:08 UTC by AutomationD

2022-01-16 07:22 UTC, psihachina commented
@AutomationD I don't see the test)

2022-01-16 07:58 UTC, AutomationD commented
> @AutomationD I don't see the test)

Tests uploaded.

2022-01-16 08:34 UTC, psihachina commented
> Tests uploaded.

Your test looks beautiful. There is something to learn. These tests can be used to write examples for this command :)

2022-01-16 15:45 UTC, psihachina requested changes

2022-01-18 15:36 UTC, AutomationD commented on cmd/main.go
> +
Let's keep it in mind, whenever you know the place, feel free to move.

2022-01-18 15:39 UTC, AutomationD commented on internal/commands/secrets/secrets_push.go
> +	AppName     string
@psihachina We also use it in Run. I'd keep it like that, any objections?

2022-01-18 15:48 UTC, psihachina approved these changes
LGTM

2022-01-18 15:54 UTC, merged